.TH KRPSIM_VERIF 1 2016-06-25 krpsim_verif
.SH NAME
krpsim_verif \- checks the trace of krpsim
.SH SYNOPSIS
.B krpsim_verif
\fI\fR<\fIfile\fR> \fR<\fIresult_to_test\fR>
.SH DESCRIPTION
.B krpsim_verif
is checker for krpsim.
.SH OPTIONS
.TP
\fB\-r\fr, \fB\--result_to_test\fr Trace of krpsim.
.TP
\fB\-f\fr, \fB\--file\fr File of configuration.

.SH AUTHOR
Written by lecorref <lecorref@gmail.com>, geam <geam@users.noreply.github.com> and adjivas <adjivas@users.noreply.github.com>.
