.TH KRPSIM 1 2016-06-25 krpsim
.SH NAME
krpsim \- runs a solver of stock
.SH SYNOPSIS
.B krpsim
\fI\fR<\fIfile\fR> \fR<\fIdelay\fR>
.SH DESCRIPTION
.B krpsim
is a manager and solver of resource.
.SH OPTIONS
.TP
\fB\-d\fr, \fB\--delay\fr Time by step.
.TP
\fB\-f\fr, \fB\--file\fr File of configuration.
.TP
\fB\-v\fr, \fB\--verbose\fr Print more information.


.SH AUTHOR
Written by lecorref <lecorref@gmail.com>, geam <geam@users.noreply.github.com> and adjivas <adjivas@users.noreply.github.com>.
